### PR TITLE
Merge last patches from LWJGL:master

### PR DESCRIPTION
**Pull request by LordNyriox**
There were a couple of small patches from December 26, 2015 in the official LWJGL 2 code that are not included here.  This PR adds them in.  

Thanks, 
~ Nyriox

### CODE REVIEW

**Comment by peterix** [comment]
What I should really do is the exact opposite. Rebase on top of upstream and send them a pull request :)

**Comment by LordNyriox** [comment]
@peterix:  Perhaps…but only if LWJGL3 can be enhanced the same way.  ;}

Thanks, 
~ Nyriox

**Comment by peterix** [comment]
Minecraft does not use LWJGL3

**Comment by LordNyriox** [comment]
Which is where?

**Comment by LordNyriox** [comment]
Also, I don't think LWJGL 2 is going to be updated anymore.  ://

**Comment by LordNyriox** [comment]
Are they still accepting PRs?

**Comment by LordNyriox** [comment]
This is what I get from making a million assumptions. :/  

I assumed LWJGL2 no longer accepted PRs…

**Comment by peterix** [comment]
Well, there's only one sure way to find out :)

**Comment by peterix** [comment]
https://github.com/LWJGL/lwjgl/pull/132

**Pull request closed without merging**
